# Generated by Django 2.2.4 on 2019-12-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191213_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avi.jpg', upload_to='Profile_pics'),
        ),
    ]
